---
- name: "Install packages"
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ apt_packages }}"

- name: "Clone scripts and config files"
  git:
    repo: "{{ i3_config_and_scripts_repo }}"
    dest: "~/.config/i3"
    version: master
  become_user: "{{ linux_user }}"